### ISSUE TITLE
Panel Animation

### ISSUE THREAD

**Issue by dukesanj** [eduardomb/jquery-panelslider#12]
Hi, thanks a million for this slide panel!

I'm not too hot on JS/JQuery and I was wondering if you could send over a snippet of code that allows the panel to animate using - jQuery Easing Plugin (version 1.3) http://gsgd.co.uk/sandbox/jquery/easing/

Ideally it would go good to have an animation for slide out and slide in, but if that's a pain then one animation would be great!

Thanks!
Sanj

**Comment by Nilpo** [comment]
You could also achieve this with pure CSS animations without adding the overhead of any other dependencies.

**Comment by dukesanj** [comment]
I've got it to work with it opening:
 #right-panel{
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
}

But it snaps shut when closing. Would you be able to assist with it animating when closing please?

This is the HTML:
<div id="right-panel" class="panel side-panel">
    <div class="side-panel-top clearfix">
        <h4 class="side-panel-title pull-left"><img src="img/vc-logo.png" alt="">VC Admin Menu</h4>
        <div class="btn btn-info btn-xs pull-right" id="close-panel-bt"><i class="fa fa-close"></i></div>
    </div>
</div>

Js:
    // Slide Panel Navigation
    $('#right-panel-link').panelslider({side: 'right', clickClose: true, duration: 380});
    $('#close-panel-bt').click(function() {
      $.panelslider.close();
    });

**Comment by dukesanj** [comment]
The other issue using CSS is the effect or transitions only happens after the page elements have moved over, I tried adjusting the duration $('#right-panel-link').panelslider({side: 'right', clickClose: true, duration: 150}); but this has no effect on the timing of CSS.

It's not a major issue to have it animated, if you're free to take a look it will be greatly appreciated... or I'm sure it will be fine without it! 
Thanks for you help so far...
Sanj

**Comment by dukesanj** [comment]
Hi Robert,
Sorry to trouble you again!
Is there a way to stop the main content from moving when the panel opens and closes?
ThanksSanj

**Comment by Nilpo** [comment]
Ok, so I had a chance to dive into the code.  The panel slider uses jQuery animation out of the gate.  You can see this by viewing the example.html file.  Adding jQuery Easing is pretty basic since you only need to add a parameter to the animate function.  I've got a working version and I will post a link to the pull request.

**Comment by Nilpo** [comment]
You can force the panel to overlap the body by removing the body animation.  You'll need to comment out the `body.animate` line for bot the open and close functions.  They look like this.

Line 49:

    //$body.animate(bodyAnimation, options.duration, options.easingOpen);

Starting at line 107:

    /*$body.animate(bodyAnimation, duration, easingClose, function() {
      active.hide();
      active.removeClass('ps-active-panel');
      _sliding = false;

      if(callback) {
        callback();
      }
    });*/

This will stop the animation for the body margin when the panel opens and closes.

**Comment by dukesanj** [comment]
Hi, 
I've commented out the code, it works the first time, but if you try to open it again it stops working.

Here's my code below:
JS:
```javascript
$(document).ready(function(){
    // Slide Panel Navigation
    $('#right-panel-link').panelslider({side: 'right', clickClose: true, duration: 450, easingOpen: 'easeInOutQuad', easingClose: 'easeOutBack'});
    $('#close-panel-bt').click(function() {
      $.panelslider.close();
    });
});
```
panelslider.js:
/*
 * jQuery Panel Slider plugin v0.1.1
 * https://github.com/eduardomb/jquery-panelslider
*/
(function($) {
  'use strict';

  var $body = $('body'),
      _sliding = false;

  function _slideIn(panel, options) {
    var panelWidth = panel.outerWidth(true),
        bodyAnimation = {},
        panelAnimation = {};

    if(panel.is(':visible') || _sliding) {
      return;
    }

    _sliding = true;
    panel.addClass('ps-active-panel').css({
      position: 'fixed',
      top: 0,
      height: '100%',
      'z-index': 999999
    });
    panel.data(options);

    switch (options.side) {
      case 'left':
        panel.css({
          left: '-' + panelWidth + 'px',
          right: 'auto'
        });
        bodyAnimation['margin-left'] = '+=' + panelWidth;
        panelAnimation.left = '+=' + panelWidth;
        break;

      case 'right':
        panel.css({
          left: 'auto',
          right: '-' + panelWidth + 'px'
        });
        bodyAnimation['margin-left'] = '-=' + panelWidth;
        panelAnimation.right = '+=' + panelWidth;
        break;
    }

    //$body.animate(bodyAnimation, options.duration, options.easingOpen);
    panel.show().animate(panelAnimation, options.duration, options.easingOpen, function() {
      _sliding = false;

      if(typeof options.onOpen == 'function') {
        options.onOpen();
      }
    });
  }

  $.panelslider = function(element, options) {
    var active = $('.ps-active-panel');
    var defaults = {
      side: 'left',     // panel side: left or right
      duration: 200,    // Transition duration in miliseconds
      clickClose: true, // If true closes panel when clicking outside it
      onOpen: null      // When supplied, function is called after the panel opens
    };

    options = $.extend({}, defaults, options);

    // If another panel is opened, close it before opening the new one
    if(active.is(':visible') && active[0] != element[0]) {
      $.panelslider.close(function() {
        _slideIn(element, options);
      });
    } else if(!active.length || active.is(':hidden')) {
      _slideIn(element, options);
    }
  };

  $.panelslider.close = function(callback) {
    var active = $('.ps-active-panel'),
        duration = active.data('duration'),
        panelWidth = active.outerWidth(true),
        bodyAnimation = {},
        panelAnimation = {};

    if(!active.length || active.is(':hidden') || _sliding) {
      return;
    }

    _sliding = true;

    switch(active.data('side')) {
      case 'left':
        bodyAnimation['margin-left'] = '-=' + panelWidth;
        panelAnimation.left = '-=' + panelWidth;
        break;

      case 'right':
        bodyAnimation['margin-left'] = '+=' + panelWidth;
        panelAnimation.right = '-=' + panelWidth;
        break;
    }

    active.animate(panelAnimation, duration);
    /*$body.animate(bodyAnimation, duration, easingClose, function() {
  active.hide();
  active.removeClass('ps-active-panel');
  _sliding = false;

  if(callback) {
    callback();
  }
});*/
  };

  // Bind click outside panel and ESC key to close panel if clickClose is true
  $(document).bind('click keyup', function(e) {
    var active = $('.ps-active-panel');

    if(e.type == 'keyup' && e.keyCode != 27) {
      return;
    }

    if(active.is(':visible') && active.data('clickClose')) {
      $.panelslider.close();
    }
  });

  // Prevent click on panel to close it
  $(document).on('click', '.ps-active-panel', function(e) {
    e.stopPropagation();
  });

  $.fn.panelslider = function(options) {
    this.click(function(e) {
      var active = $('.ps-active-panel'),
          panel = $(this.getAttribute('href'));

      // Close panel if it is already opened otherwise open it
      if (active.is(':visible') && panel[0] == active[0]) {
        $.panelslider.close();
      } else {
        $.panelslider(panel, options);
      }

      e.preventDefault();
      e.stopPropagation();
    });

    return this;
  };
})(jQuery);

**Comment by Nilpo** [comment]
You need to use the updated script file from my fork.  You can grab it from my pull request.

**Comment by dukesanj** [comment]
Sorry about this! I still have the same issue, the body no longer moves which is perfect!
But the panel will only open and close once.
Here's my code:

```javascript
/*
 * jQuery Panel Slider plugin v0.1.2
 * https://github.com/eduardomb/jquery-panelslider
*/
(function($) {
  'use strict';

  var $body = $('body'),
      _sliding = false;

  function _slideIn(panel, options) {
    var panelWidth = panel.outerWidth(true),
        bodyAnimation = {},
        panelAnimation = {};

    if(panel.is(':visible') || _sliding) {
      return;
    }

    _sliding = true;
    panel.addClass('ps-active-panel').css({
      position: 'fixed',
      top: 0,
      height: '100%',
      'z-index': 999999
    });
    panel.data(options);

    switch (options.side) {
      case 'left':
        panel.css({
          left: '-' + panelWidth + 'px',
          right: 'auto'
        });
        bodyAnimation['margin-left'] = '+=' + panelWidth;
        panelAnimation.left = '+=' + panelWidth;
        break;

      case 'right':
        panel.css({
          left: 'auto',
          right: '-' + panelWidth + 'px'
        });
        bodyAnimation['margin-left'] = '-=' + panelWidth;
        panelAnimation.right = '+=' + panelWidth;
        break;
    }

    // $body.animate(bodyAnimation, options.duration, options.easingOpen);
    panel.show().animate(panelAnimation, options.duration, options.easingOpen, function() {
      _sliding = false;

      if(typeof options.onOpen == 'function') {
        options.onOpen();
      }
    });
  }

  $.panelslider = function(element, options) {
    var active = $('.ps-active-panel');
    var defaults = {
      side: 'left',     // panel side: left or right
      duration: 200,    // Transition duration in miliseconds
      clickClose: true, // If true closes panel when clicking outside it
      onOpen: null,     // When supplied, function is called after the panel opens
      easingOpen: null, // Easing method for opening, requires jQuery Easing Plugin 1.3
      easingClose: null // Easing method for opening, requires jQuery Easing Plugin 1.3
    };

    options = $.extend({}, defaults, options);
    // If another panel is opened, close it before opening the new one
    if(active.is(':visible') && active[0] != element[0]) {
      $.panelslider.close(function() {
        _slideIn(element, options);
      });
    } else if(!active.length || active.is(':hidden')) {
      _slideIn(element, options);
    }
  };

  $.panelslider.close = function(callback) {
    var active = $('.ps-active-panel'),
        duration = active.data('duration'),
        panelWidth = active.outerWidth(true),
        bodyAnimation = {},
        panelAnimation = {},
        easingClose = active.data('easingClose');

    if(!active.length || active.is(':hidden') || _sliding) {
      return;
    }

    _sliding = true;

    switch(active.data('side')) {
      case 'left':
        bodyAnimation['margin-left'] = '-=' + panelWidth;
        panelAnimation.left = '-=' + panelWidth;
        break;

      case 'right':
        bodyAnimation['margin-left'] = '+=' + panelWidth;
        panelAnimation.right = '-=' + panelWidth;
        break;
    }
    active.animate(panelAnimation, duration, easingClose);
    // $body.animate(bodyAnimation, duration, easingClose, function() {
    //   active.hide();
    //   active.removeClass('ps-active-panel');
    //   _sliding = false;

    //   if(callback) {
    //     callback();
    //   }
    // });
  };

  // Bind click outside panel and ESC key to close panel if clickClose is true
  $(document).bind('click keyup', function(e) {
    var active = $('.ps-active-panel');

    if(e.type == 'keyup' && e.keyCode != 27) {
      return;
    }

    if(active.is(':visible') && active.data('clickClose')) {
      $.panelslider.close();
    }
  });

  // Prevent click on panel to close it
  $(document).on('click', '.ps-active-panel', function(e) {
    e.stopPropagation();
  });

  $.fn.panelslider = function(options) {
    this.click(function(e) {
      var active = $('.ps-active-panel'),
          panel = $(this.getAttribute('href'));

      // Close panel if it is already opened otherwise open it
      if (active.is(':visible') && panel[0] == active[0]) {
        $.panelslider.close();
      } else {
        $.panelslider(panel, options);
      }

      e.preventDefault();
      e.stopPropagation();
    });

    return this;
  };
})(jQuery);
```

**Comment by Nilpo** [comment]
Are you loading all of your JavaScript at the bottom of the page?

**Comment by dukesanj** [comment]
no its in a separate page, but I've tried to add it to the page, still got the same issue.
I removed all other scripts too, same problem.
Is there an email address where I can zip up the page and send it over. Don't really want to post it here.

**Comment by Nilpo** [comment]
devnilpo@gmail.com

**Comment by dukesanj** [comment]
On it's way to you!
Thank you very much for your assistance...

**Comment by Nilpo** [comment]
Sorry.  I had you comment out too many lines on that last edit.  It should look like this:

    // $body.animate(bodyAnimation, duration, easingClose, function() {
       active.hide();
       active.removeClass('ps-active-panel');
       _sliding = false;
    
       if(callback) {
         callback();
       }
    // });

**Comment by dukesanj** [comment]
Hi that worked fine!
The issue now is the ease animation for closing the panel is not working. It snaps shut.
Thanks...
Sanj

**Comment by dukesanj** [comment]
Hi, sorry to bother you again!
Just wondering if you had a chance to see what the issue was when the slider closes.
The ease animation is not applying when closing and only when it opens.
Note -  I've applied the fix for stopping the body from moving too.

Thanks
Sanj

**Comment by duzun** [comment]
My PR #11 uses CSS to animate the panel and also introduces few events to handle panel close/open and CSS animation end.
For the sake of performance and especially on mobile devices all animations should be CSS.
You can see it working on https://duzun.me.

Cheers

**Comment by eduardomb** [comment]
Hi @dukesanj. Sorry for taking too long to answer. If you are still willing to use the plugin the good news is since version 1.0.0 (Inspired by @duzun CSS implementation) animation and positioning are handled by user's CSS.

This gives you power to customize the panel animation in any way you want, e.g., using easing effects. There is a CSS implementation of left / right panels in _example.html_. In this example, if you change the `transition: transform .2s` to `transition: transform .5s ease-in-out` you'll get the effect you want.

Let me know if you face any problems when doing this.
