### ISSUE TITLE
Add a Class to the Body

### ISSUE THREAD

**Issue by WS-Theme** [eduardomb/jquery-panelslider#17]
I think it will be a pretty good idea to add a Class to the Body when the Panel is opening, for example .addClass('panelslider-open'); and .removeClass('panelslider-open');

Only a idea if someone want to add for example a Overlay over the whole Main Body for example! 

I made something similar with the Sidr Plugin here: http://www.place4nails.de/
(Click Facebook or Impressum)

Cheers, Oli

**Comment by Nilpo** [comment]
Just out of curiosity, what would be the purpose of this?  You can already target the panel when it's open or closed.

**Comment by WS-Theme** [comment]
Like I have write above, to simply add a dark Overlay to the rest of the Body page, so you can better focus the Content in the Panel! At the moment this isn't possible cause only the Panel get's a active Class and not the Content or the Body!

**Comment by Nilpo** [comment]
You can use the callbacks for this.

**Comment by WS-Theme** [comment]
All right, was only a suggestion! Of course also possible with Callback :+1:

**Comment by Nilpo** [comment]
If it doesn't get added, you could do it like this.

Add a class when the panel opens around line 21:

        _sliding = true;
        $body.addClass('ps-active');                  // <---  add class here
        panel.addClass('ps-active-panel').css({
          position: 'fixed',
          top: 0,
          height: '100%',
          'z-index': 999999
        });

Remove class when panel closes around line 115:

        $body.animate(bodyAnimation, duration, function() {
          active.hide();
          active.removeClass('ps-active-panel');
          _sliding = false;
    
          if(callback) {
            callback();
          }
        }).removeClass('ps-active');                 // <-- remove here by chaining it after the animation

This code is untested but it should be good to go.

**Comment by WS-Theme** [comment]
Awesome my friend :smile:

**Comment by Zaanmedia** [comment]
Somehow i don't see any class get added in my body tag? What am i doing wrong here also in the demo i don't see that the body is getting any class.

**Comment by Nilpo** [comment]
How are you checking it?  What browser are you using?

**Comment by eduardomb** [comment]
Upgrade to the latest version. Version `1.0.0` adds the class `ps-active` when panel is open. The class name can be changed passing the `bodyClass` on initialisation. Please, let me know if you have any problems.
