### ISSUE TITLE
There seems to be an error in the documentation

### ISSUE THREAD

**Issue by gekum** [eduardomb/jquery-panelslider#2]
First, thanks for creating this panel slider!

While trying out the panelslider today I came across what looks like an error in the Usage section of the README.md. According to the instructions, I should invoke .panelslider() on the panel element #my-panel, which ends up not working, and no panel is created. In contrast, the code on the demo page invokes .panelslider() on the the #my-link hyperlink instead of #my-panel, which does work.

Thank you

**Comment by eduardomb** [comment]
Fixed on https://github.com/eduardomb/jquery-panelslider/pull/19
