### ISSUE TITLE
How invoke panel slider without a click

### ISSUE THREAD

**Issue by robgnyc** [eduardomb/jquery-panelslider#25]
I'm trying to invoke panel slider when an ajax call comes back successfully using your example:

"You can also invoke panelslider() directly
$.panelslider($('#my-link'));"

However this doesn't work. It works with the button, but I'd like to fire the panelslider event directly in a successful ajax reply.

**Comment by Nilpo** [comment]
Can you post the code you are trying to use?

**Comment by robgnyc** [comment]
`$.ajax( {
        url: url,
        method: "GET",
        dataType: "jsonp",
        success: function(response) {
            var data = response.data;
        $.panelslider($('#my-link'));
        console.log(data);

```
        data.forEach(function(data) {
            var url = data.images.thumbnail.url;
            var imageEl = $('<img src="' + url +'" />');


            $('#my-panel').append(imageEl);
        })
    }
})`
```

**Comment by Nilpo** [comment]
Do you have a link somewhere else on your page with the ID "my-link"?  It should look something like this.

```
<a id="my-link" href="#my-panel">Open panel</a>
```

**Comment by robgnyc** [comment]
Yes I do.

```
<div id="my-panel" class="image-results-view text-center">

  <h1>Choose Images from your feed:</h1>
</div>

<a id="my-link" href="#my-panel">Open panel</a>
  <!-- js -->
```

**Comment by Nilpo** [comment]
Are you getting any errors the the JS console?

**Comment by robgnyc** [comment]
No errors. It just doesn't fire. Is there a way to pass the target to it directly without going through the link?

**Comment by robgnyc** [comment]
I created a very simple example to show how it doesn't fire on it's own:

http://robertgruber.com/final-project/test.html

```
Jquery:
$(document).ready(function() {

        $.panelslider($('#my-link'));


});

html
<div id="my-panel" class="image-results-view text-center">

  <h1>Choose Images from your feed:</h1>
</div>

<a id="my-link" href="#my-panel">Open panel</a>
```

**Comment by Nilpo** [comment]
It works perfectly. I just added the line to click the link.

```
$('#my-link').click();  // opens the panel by "clicking" the link.
```

**Comment by Nilpo** [comment]
It's occurring to me that perhaps the language in the readme is bad.  Invoking the panel simply means to attach it to a link that can trigger it. You still need to actually click the link.

**Comment by robgnyc** [comment]
Yes, I was hoping to launch it from a function without a click when a ajax response is successful it slides open.

I mis-interpreted your read me.

Is there any way to do this? I can probably figure it out.

Also you should probably mention that all click functions in an open panel are suppressed by line 84:

```
// Prevent click on panel to close it
  $(document).on('click', '.ps-active-panel', function(e) {
    e.stopPropagation();
  });
```

unless you explicitly allow them by targeting your element from the document down. Was driving me crazy till I figured it out.
