### ISSUE TITLE
Not cleanly close the panel

### ISSUE THREAD

**Issue by moafred** [eduardomb/jquery-panelslider#4]
In my case, the panel is note hide/removeClass, just move outisde.
I fixed it by doing this:

```
active.animate(panelAnimation, duration, function() {
//    $body.animate(bodyAnimation, duration, function() {
      active.hide();
      active.removeClass('ps-active-panel');
      _sliding = false;

      if(callback) {
        callback();
      }
    });
```

Don't understand why it's working in the demo.

**Comment by eduardomb** [comment]
Closing due inactivity. @moafred please open a new issue if you're still having problems.
