### ISSUE TITLE
Open just one time

### ISSUE THREAD

**Issue by Shnalla** [eduardomb/jquery-panelslider#5]
Hi, 

Thank you for this script. 
I have a little problem : when I open the panel the first time, it works well. Second time, it's impossible to open it again.

Do you have any idea ?

**Comment by eduardomb** [comment]
Sorry for taking this long to respond. There was indeed a bug that prevent the plugin to work correctly when loaded in head (https://github.com/eduardomb/jquery-panelslider/issues/3). It was fixed on `1.0.0`. There are breaking changes though. I've updated **README.md** with new instructions of how to use the plugin. Please let me know if you have trouble upgrading.
